### PR TITLE
Fix #26

### LINKED ISSUE #26: Titles revert on New File/Delete File
I just noticed the project names dropped (as well as the git statuses) when I deleted a file in the folder... I refreshed and added a file and watched the names drop again. There must be an event that we're missing.

### PR DESCRIPTION
**Pull request by jsg2021**

### CODE REVIEW

**Comment by jsg2021** [comment]
[tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) Will need something simular.

**Comment by jsg2021** [comment]
I opened a similar PR on https://github.com/subesokun/atom-tree-view-git-status/pull/60

**Comment by subesokun** [comment]
Awesome, thanks a lot for your contributions 😄! This week will be a bit busy so I'll try to review and merge your changes by end of next week.

**Comment by jsg2021** [comment]
I've been running with the linked in local changes from these PRs for the last week, feels pretty solid... As a further optimization, we could even remove the other atom event listeners and just respond to the MutationObserver's callback... but I'll leave it as it is for now.

**Comment by subesokun** [comment]
Thanks again for your support and patience 👏! As you've mentioned already the MutationObserver could completely replace the tree-view events for updating the tree view. Initially I thought using those tree-view events might be a good idea as there more stable in terms of API as compared to the DOM tree but it's hard to track all events :/ For the time being I'll keep both inside.

**Pull request merged**
