### PR TITLE
live update for the project name

### PR DESCRIPTION
**Pull request by rodrigopmatias**
proposal to fix issue #1

### CODE REVIEW

**Comment by subesokun** [comment]
@rodrigopmatias Awesome! Thanks a lot for you contribution :) I'll try to review it tomorrow and give then some feedback.

**Comment by subesokun** [comment]
I had now a chance to review your PR but the file polling in the watcher.coffee looks for me not like the solution I want to go with. After having a look on the `tree-view` I noticed that they're using `pathwatcher` which seems for me like the better solution. On a yet private feature branch I've already an experimental version running with looks good so far. I'd be great if you could review it once I publish it :)

**Comment by rodrigopmatias** [comment]
:horse_racing: now is better, small code and using fs.watchFile

**Comment by rodrigopmatias** [comment]
:+1: now ready

**Comment by rodrigopmatias** [comment]
@subesokun can you review the code?

**Comment by subesokun** [comment]
@rodrigopmatias Sorry for the delay. A new release containing the live-reload feature and some other bug fixes is almost ready and I'll try to push everything by this weekend.

**Comment by subesokun** [comment]
@rodrigopmatias I had a look on you latest PR but some stuff like removal of file watcher subscriptions when deactivating the package have been missing and I wanted to rework a bit the way how project-view works. Hence I came up with a different solution in commit https://github.com/subesokun/atom-project-view/commit/0e54739202c1dc18ea667801afcb9833207d1247. I'd be awesome if you could give a feedback if you face any issues or bugs and really thanks for your initial PR!

**Pull request closed without merging**
